services:
  db:
    image: postgres:latest
    container_name: roomiesapp-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-flawbert}
      POSTGRES_PASSWORD: ${DB_PASS:-fl2003}
      POSTGRES_DB: roomiesapp
    ports:
      - "5432:5432"
