services:
  db:
    image: postgres:latest
    container_name: tripmaker-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: tripmaker
    ports:
      - "5432:5432"
